### ISSUE TITLE
docker directory missing from subt_hello_world

### ISSUE THREAD

**Issue by willydlw** [osrf/subt_hello_world#3]
Following the 02_docker_and_slam.md instructions. There is no docker directory in the subt_hello_world path.

![Screenshot from 2020-05-21 18-00-38](https://user-images.githubusercontent.com/4870516/82617357-113b1480-9b8d-11ea-8b68-d41b21a86ba5.png)

**Comment by angelacmaio** [comment]
Thanks, looks like some items are missing. Try PR #4

**Comment by adlarkin** [comment]
I've just merged PR #4, so the repository should now have all of the necessary files to go through posts 1 and 2. @willydlw can you try again and let me know if this works for you? If you can work through post 2, I will close this issue.

**Comment by willydlw** [comment]
Thank you, the docker folder is there now. ./build_common_image.bash produces a broken package error. 
![Screenshot from 2020-05-22 19-34-33](https://user-images.githubusercontent.com/4870516/82718985-a27cba80-9c63-11ea-88a4-61b4c7341261.png)

**Comment by adlarkin** [comment]
It looks like somebody else is facing this same issue. Since we have now added in the docker files, I am going to close this issue and address this problem in the thread for issue #5.
